// Generated by gencpp from file beginner_tutorials/AIService.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_AISERVICE_H
#define BEGINNER_TUTORIALS_MESSAGE_AISERVICE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/AIServiceRequest.h>
#include <beginner_tutorials/AIServiceResponse.h>


namespace beginner_tutorials
{

struct AIService
{

typedef AIServiceRequest Request;
typedef AIServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AIService
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::AIService > {
  static const char* value()
  {
    return "ebf5e3c3cf0200651dc17aec0c4cde8e";
  }

  static const char* value(const ::beginner_tutorials::AIService&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::AIService > {
  static const char* value()
  {
    return "beginner_tutorials/AIService";
  }

  static const char* value(const ::beginner_tutorials::AIService&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::AIServiceRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::AIService >
template<>
struct MD5Sum< ::beginner_tutorials::AIServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AIService >::value();
  }
  static const char* value(const ::beginner_tutorials::AIServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AIServiceRequest> should match
// service_traits::DataType< ::beginner_tutorials::AIService >
template<>
struct DataType< ::beginner_tutorials::AIServiceRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AIService >::value();
  }
  static const char* value(const ::beginner_tutorials::AIServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::AIServiceResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::AIService >
template<>
struct MD5Sum< ::beginner_tutorials::AIServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AIService >::value();
  }
  static const char* value(const ::beginner_tutorials::AIServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AIServiceResponse> should match
// service_traits::DataType< ::beginner_tutorials::AIService >
template<>
struct DataType< ::beginner_tutorials::AIServiceResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AIService >::value();
  }
  static const char* value(const ::beginner_tutorials::AIServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_AISERVICE_H
